/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiUserTweetsRouteImport } from './routes/api/user-tweets'
import { Route as ApiUserInfoRouteImport } from './routes/api/user-info'
import { Route as ApiThreadRouteImport } from './routes/api/thread'
import { Route as ApiArticleRouteImport } from './routes/api/article'
import { Route as SourceHostSplatRouteImport } from './routes/$sourceHost/$'
import { Route as ApiFetchJobsSplatRouteImport } from './routes/api/fetch-jobs/$'
import { Route as ApiCheckoutStatusRouteImport } from './routes/api/checkout/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFetchJobsJobIdTweetsRouteImport } from './routes/api/fetch-jobs/$jobId/tweets'
import { Route as ApiFetchJobsJobIdStopRouteImport } from './routes/api/fetch-jobs/$jobId/stop'
import { Route as ApiFetchJobsJobIdStatusRouteImport } from './routes/api/fetch-jobs/$jobId/status'

const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserTweetsRoute = ApiUserTweetsRouteImport.update({
  id: '/api/user-tweets',
  path: '/api/user-tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserInfoRoute = ApiUserInfoRouteImport.update({
  id: '/api/user-info',
  path: '/api/user-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadRoute = ApiThreadRouteImport.update({
  id: '/api/thread',
  path: '/api/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticleRoute = ApiArticleRouteImport.update({
  id: '/api/article',
  path: '/api/article',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceHostSplatRoute = SourceHostSplatRouteImport.update({
  id: '/$sourceHost/$',
  path: '/$sourceHost/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchJobsSplatRoute = ApiFetchJobsSplatRouteImport.update({
  id: '/api/fetch-jobs/$',
  path: '/api/fetch-jobs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutStatusRoute = ApiCheckoutStatusRouteImport.update({
  id: '/api/checkout/status',
  path: '/api/checkout/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchJobsJobIdTweetsRoute = ApiFetchJobsJobIdTweetsRouteImport.update({
  id: '/api/fetch-jobs/$jobId/tweets',
  path: '/api/fetch-jobs/$jobId/tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchJobsJobIdStopRoute = ApiFetchJobsJobIdStopRouteImport.update({
  id: '/api/fetch-jobs/$jobId/stop',
  path: '/api/fetch-jobs/$jobId/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchJobsJobIdStatusRoute = ApiFetchJobsJobIdStatusRouteImport.update({
  id: '/api/fetch-jobs/$jobId/status',
  path: '/api/fetch-jobs/$jobId/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/$sourceHost/$': typeof SourceHostSplatRoute
  '/api/article': typeof ApiArticleRoute
  '/api/thread': typeof ApiThreadRoute
  '/api/user-info': typeof ApiUserInfoRoute
  '/api/user-tweets': typeof ApiUserTweetsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/status': typeof ApiCheckoutStatusRoute
  '/api/fetch-jobs/$': typeof ApiFetchJobsSplatRoute
  '/api/fetch-jobs/$jobId/status': typeof ApiFetchJobsJobIdStatusRoute
  '/api/fetch-jobs/$jobId/stop': typeof ApiFetchJobsJobIdStopRoute
  '/api/fetch-jobs/$jobId/tweets': typeof ApiFetchJobsJobIdTweetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/$sourceHost/$': typeof SourceHostSplatRoute
  '/api/article': typeof ApiArticleRoute
  '/api/thread': typeof ApiThreadRoute
  '/api/user-info': typeof ApiUserInfoRoute
  '/api/user-tweets': typeof ApiUserTweetsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/status': typeof ApiCheckoutStatusRoute
  '/api/fetch-jobs/$': typeof ApiFetchJobsSplatRoute
  '/api/fetch-jobs/$jobId/status': typeof ApiFetchJobsJobIdStatusRoute
  '/api/fetch-jobs/$jobId/stop': typeof ApiFetchJobsJobIdStopRoute
  '/api/fetch-jobs/$jobId/tweets': typeof ApiFetchJobsJobIdTweetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/$sourceHost/$': typeof SourceHostSplatRoute
  '/api/article': typeof ApiArticleRoute
  '/api/thread': typeof ApiThreadRoute
  '/api/user-info': typeof ApiUserInfoRoute
  '/api/user-tweets': typeof ApiUserTweetsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/status': typeof ApiCheckoutStatusRoute
  '/api/fetch-jobs/$': typeof ApiFetchJobsSplatRoute
  '/api/fetch-jobs/$jobId/status': typeof ApiFetchJobsJobIdStatusRoute
  '/api/fetch-jobs/$jobId/stop': typeof ApiFetchJobsJobIdStopRoute
  '/api/fetch-jobs/$jobId/tweets': typeof ApiFetchJobsJobIdTweetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/$sourceHost/$'
    | '/api/article'
    | '/api/thread'
    | '/api/user-info'
    | '/api/user-tweets'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/checkout/status'
    | '/api/fetch-jobs/$'
    | '/api/fetch-jobs/$jobId/status'
    | '/api/fetch-jobs/$jobId/stop'
    | '/api/fetch-jobs/$jobId/tweets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/$sourceHost/$'
    | '/api/article'
    | '/api/thread'
    | '/api/user-info'
    | '/api/user-tweets'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/checkout/status'
    | '/api/fetch-jobs/$'
    | '/api/fetch-jobs/$jobId/status'
    | '/api/fetch-jobs/$jobId/stop'
    | '/api/fetch-jobs/$jobId/tweets'
  id:
    | '__root__'
    | '/'
    | '/auth-error'
    | '/$sourceHost/$'
    | '/api/article'
    | '/api/thread'
    | '/api/user-info'
    | '/api/user-tweets'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/checkout/status'
    | '/api/fetch-jobs/$'
    | '/api/fetch-jobs/$jobId/status'
    | '/api/fetch-jobs/$jobId/stop'
    | '/api/fetch-jobs/$jobId/tweets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthErrorRoute: typeof AuthErrorRoute
  SourceHostSplatRoute: typeof SourceHostSplatRoute
  ApiArticleRoute: typeof ApiArticleRoute
  ApiThreadRoute: typeof ApiThreadRoute
  ApiUserInfoRoute: typeof ApiUserInfoRoute
  ApiUserTweetsRoute: typeof ApiUserTweetsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutStatusRoute: typeof ApiCheckoutStatusRoute
  ApiFetchJobsSplatRoute: typeof ApiFetchJobsSplatRoute
  ApiFetchJobsJobIdStatusRoute: typeof ApiFetchJobsJobIdStatusRoute
  ApiFetchJobsJobIdStopRoute: typeof ApiFetchJobsJobIdStopRoute
  ApiFetchJobsJobIdTweetsRoute: typeof ApiFetchJobsJobIdTweetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-tweets': {
      id: '/api/user-tweets'
      path: '/api/user-tweets'
      fullPath: '/api/user-tweets'
      preLoaderRoute: typeof ApiUserTweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-info': {
      id: '/api/user-info'
      path: '/api/user-info'
      fullPath: '/api/user-info'
      preLoaderRoute: typeof ApiUserInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thread': {
      id: '/api/thread'
      path: '/api/thread'
      fullPath: '/api/thread'
      preLoaderRoute: typeof ApiThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/article': {
      id: '/api/article'
      path: '/api/article'
      fullPath: '/api/article'
      preLoaderRoute: typeof ApiArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sourceHost/$': {
      id: '/$sourceHost/$'
      path: '/$sourceHost/$'
      fullPath: '/$sourceHost/$'
      preLoaderRoute: typeof SourceHostSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-jobs/$': {
      id: '/api/fetch-jobs/$'
      path: '/api/fetch-jobs/$'
      fullPath: '/api/fetch-jobs/$'
      preLoaderRoute: typeof ApiFetchJobsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/status': {
      id: '/api/checkout/status'
      path: '/api/checkout/status'
      fullPath: '/api/checkout/status'
      preLoaderRoute: typeof ApiCheckoutStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-jobs/$jobId/tweets': {
      id: '/api/fetch-jobs/$jobId/tweets'
      path: '/api/fetch-jobs/$jobId/tweets'
      fullPath: '/api/fetch-jobs/$jobId/tweets'
      preLoaderRoute: typeof ApiFetchJobsJobIdTweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-jobs/$jobId/stop': {
      id: '/api/fetch-jobs/$jobId/stop'
      path: '/api/fetch-jobs/$jobId/stop'
      fullPath: '/api/fetch-jobs/$jobId/stop'
      preLoaderRoute: typeof ApiFetchJobsJobIdStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-jobs/$jobId/status': {
      id: '/api/fetch-jobs/$jobId/status'
      path: '/api/fetch-jobs/$jobId/status'
      fullPath: '/api/fetch-jobs/$jobId/status'
      preLoaderRoute: typeof ApiFetchJobsJobIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthErrorRoute: AuthErrorRoute,
  SourceHostSplatRoute: SourceHostSplatRoute,
  ApiArticleRoute: ApiArticleRoute,
  ApiThreadRoute: ApiThreadRoute,
  ApiUserInfoRoute: ApiUserInfoRoute,
  ApiUserTweetsRoute: ApiUserTweetsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutStatusRoute: ApiCheckoutStatusRoute,
  ApiFetchJobsSplatRoute: ApiFetchJobsSplatRoute,
  ApiFetchJobsJobIdStatusRoute: ApiFetchJobsJobIdStatusRoute,
  ApiFetchJobsJobIdStopRoute: ApiFetchJobsJobIdStopRoute,
  ApiFetchJobsJobIdTweetsRoute: ApiFetchJobsJobIdTweetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
